/**
 * CodeRun tool — write, execute, and capture output in one step.
 *
 * Supports Python, Node.js, Bash, and TypeScript.
 * Scripts are written to sessions/<session_id>/scripts/ and executed via sandbox.
 * Returns stdout, stderr, exit code, and any files generated by the script.
 *
 * Permission: "execute"
 */

import { z } from "zod";
import { mkdir, readdir, writeFile } from "fs/promises";
import { join, resolve } from "path";
import { ok, err } from "./base.js";
import type { Tool, ToolExecutionContext, ToolExecuteResult } from "./base.js";
import { sandboxManager } from "../security/sandbox.js";

const MAX_OUTPUT = 50_000;

const INTERPRETERS: Record<string, { cmd: (file: string) => string; ext: string }> = {
  python: { cmd: (f) => `python3 ${f}`, ext: "py" },
  node: { cmd: (f) => `node ${f}`, ext: "js" },
  bash: { cmd: (f) => `bash ${f}`, ext: "sh" },
  typescript: { cmd: (f) => `npx tsx ${f}`, ext: "ts" },
};

const CodeRunInputSchema = z.object({
  language: z.enum(["python", "node", "bash", "typescript"]).describe("Programming language to execute"),
  code: z.string().describe("The code to execute"),
  filename: z.string().optional().describe("Optional filename (default: auto-generated)"),
  timeout_ms: z.number().optional().default(60000).describe("Execution timeout in ms"),
});

type CodeRunInput = z.infer<typeof CodeRunInputSchema>;

export const codeRunTool: Tool<CodeRunInput> = {
  name: "code_run",
  description:
    "Write code to a file and execute it, capturing stdout, stderr, exit code, and any generated files. Supports python, node, bash, typescript.",
  schema: CodeRunInputSchema,
  permission_level: "execute",

  async execute(input: CodeRunInput, context: ToolExecutionContext): Promise<ToolExecuteResult> {
    if (context.plan_mode) {
      return ok(
        `[PLAN MODE] Would execute ${input.language} script:\n${input.code}`
      );
    }

    const interp = INTERPRETERS[input.language];
    const ext = interp.ext;
    const filename = input.filename ?? `script_${Date.now()}.${ext}`;

    // Create scripts directory
    const scriptsDir = resolve(context.cwd, "sessions", context.session.id, "scripts");
    try {
      await mkdir(scriptsDir, { recursive: true });
    } catch (e) {
      return err(`Cannot create scripts directory: ${String(e)}`);
    }

    const scriptPath = join(scriptsDir, filename);

    // Write script
    try {
      await writeFile(scriptPath, input.code, "utf-8");
    } catch (e) {
      return err(`Cannot write script: ${String(e)}`);
    }

    // Snapshot directory contents before execution
    let filesBefore: Set<string>;
    try {
      filesBefore = new Set(await readdir(scriptsDir));
    } catch {
      filesBefore = new Set();
    }

    // Execute via sandbox
    const command = interp.cmd(scriptPath);
    const result = await sandboxManager.exec(command, context.cwd, context.env);

    if (result.blocked) {
      return err(`[Blocked] ${result.blockReason}`);
    }

    // Scan for newly generated files
    let generatedFiles: string[] = [];
    try {
      const filesAfter = await readdir(scriptsDir);
      generatedFiles = filesAfter.filter((f) => !filesBefore.has(f) && f !== filename);
    } catch {
      // ignore scan errors
    }

    // Build output
    let stdout = result.stdout;
    let stderr = result.stderr;

    if (stdout.length > MAX_OUTPUT) {
      stdout = stdout.slice(0, MAX_OUTPUT) + `\n...[truncated]`;
    }
    if (stderr.length > MAX_OUTPUT) {
      stderr = stderr.slice(0, MAX_OUTPUT) + `\n...[truncated]`;
    }

    const output = JSON.stringify(
      {
        stdout: stdout.trim(),
        stderr: stderr.trim(),
        exit_code: result.exitCode,
        script_path: scriptPath,
        generated_files: generatedFiles,
        timed_out: result.timedOut ?? false,
      },
      null,
      2
    );

    if (result.exitCode !== 0) {
      return err(output);
    }

    return ok(output);
  },
};
